### ISSUE TITLE
Feature Request Review

### ISSUE THREAD

**Issue by mp1pro** [alexstouffer/bwa-u4-feature-request#1]
Adding the ability to trigger the savePlaylist() function by pressing enter button will indeed make the app faster to navigate. We can combine key check events to ensure cross compatibility for browsers. The code used for ES7 is valid in ES6 in this case. Both will need transpilation using babel. We would also still need to bind the method in the constructor. Here is a code example;
```
  handleEnterForPlaylist(event) {
    if(event.keyCode === 13 || event.charCode==13 || event.key === "Enter") {
      this.saveplayList();
    }
}
```
and
`<input onKeyDown={this.handleEnterForPlaylist}/>`

Great Feature Request

**Comment by alexstouffer** [comment]
Thanks for the notes on this feature request. I'll definitely have to transpile this to previous ES versions, and it looks like your conditional statement may work for previous versions.
